export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as VerifyEmailPage } from './VerifyEmailPage';
export { default as ForgotPasswordPage } from './ForgotPasswordPage';
export { default as ResetPasswordPage } from './ResetPasswordPage';
export { default as UserDashboard } from './UserDashboard';
export { default as AdminDashboard } from './AdminDashboard';
export { default as SuperAdminDashboard } from './SuperAdminDashboard';
